import { AZDivider } from "./AZDivider/AZDivider.js";
import { AZButton } from "./AZButton/AZButton.js";
import { AZInput } from "./AZInput/AZInput.js";
import { AZSelect } from "./AZSelect/AZSelect.js";
import { AZLink } from "./AZLink/AZLink.js";
import { AZUpload } from "./AZUpload/AZUpload.js";
import { AZOTP } from "./AZOTP/AZOTP.js";
import { AZPassword } from "./AZPassword/AZPassword.js";
import { AZRegisterStep } from "./AZRegisterSteps/AZRegisterStep.js";
import { AZRegisterSteps } from "./AZRegisterSteps/AZRegisterSteps.js";
import { AZRegisterStepDivider } from "./AZRegisterSteps/AZRegisterStepDivider.js";
import { AZLogin } from "./AZLogin/AZLogin.js";
import { AZLoginLeftDiv } from "./AZLogin/AZLoginLeftDiv.js";
import { AZLoginRightDiv } from "./AZLogin/AZLoginRightDiv.js";
import { AZRegister } from "./AZRegister/components/Register/Register.js";
import { AZRegisterLeftDiv } from "./AZRegister/components/LeftDiv/LeftDiv.js";
import { AZRegisterRightDiv } from "./AZRegister/components/RightDiv/RightDiv.js";
import { AZRegisterCompanyStep1 } from "./AZRegister/components/Steps/Company/Step1.js";
import { AZRegisterCompanyStep2 } from "./AZRegister/components/Steps/Company/Step2.js";
import { AZRegisterCompanyStep3 } from "./AZRegister/components/Steps/Company/Step3.js";
import { AZRegisterCompanyStep4 } from "./AZRegister/components/Steps/Company/Step4.js";
import { AZRegisterCompanyStep5 } from "./AZRegister/components/Steps/Company/Step5.js";
import { AZRegisterCompanyStep6 } from "./AZRegister/components/Steps/Company/Step6.js";
import { AZRegisterCompanyStep7 } from "./AZRegister/components/Steps/Company/Step7.js";
import { AZRegisterPersonStep1 } from "./AZRegister/components/Steps/Person/Step1.js";
import { AZRegisterPersonStep2 } from "./AZRegister/components/Steps/Person/Step2.js";
import { AZRegisterPersonStep3 } from "./AZRegister/components/Steps/Person/Step3.js";
import { AZRegisterPersonStep4 } from "./AZRegister/components/Steps/Person/Step4.js";
import { AZRegisterPersonStep5 } from "./AZRegister/components/Steps/Person/Step5.js";
import { AZRegisterPersonStep6 } from "./AZRegister/components/Steps/Person/Step6.js";
import { AZProduct } from "./AZProducts/AZProduct.js";
import { AZClient } from "./AZClients/AZClient.js";
import { AZClientProduct } from "./AZClients/AZClientProduct.js";
import { AZProductsRightDiv } from "./AZProducts/AZProductsRightDiv.js";
import { AZClientsRightDiv } from "./AZClients/AZClientsRightDiv.js";
import { AZSlider } from "./AZSlider/AZSlider.js";
import { AZSwitch } from "./AZSwitch/AZSwitch.js";
import { AZFilters } from "./AZProducts/AZFilters.js";
import { AZProducts } from "./AZProducts/AZProducts.js";
import { AZClients } from "./AZClients/AZClients.js";
import { AZHeader } from "./AZHeader/AZHeader.js";
import { AZHeaderDivider } from "./AZHeader/AZHeaderDivider.js";
import { AZMenu } from "./AZMenu/AZMenu.js";
import { AZMenuItem } from "./AZMenu/AZMenuItem.js";
import { AZSplash } from "./AZRegister/components/Splash/Splash.js";
import { AZRadio } from "./AZRadio/AZRadio.js";

customElements.define('az-register-company-step1', AZRegisterCompanyStep1);
customElements.define('az-register-company-step2', AZRegisterCompanyStep2);
customElements.define('az-register-company-step3', AZRegisterCompanyStep3);
customElements.define('az-register-company-step4', AZRegisterCompanyStep4);
customElements.define('az-register-company-step5', AZRegisterCompanyStep5);
customElements.define('az-register-company-step6', AZRegisterCompanyStep6);
customElements.define('az-register-company-step7', AZRegisterCompanyStep7);
customElements.define('az-register-person-step1', AZRegisterPersonStep1);
customElements.define('az-register-person-step2', AZRegisterPersonStep2);
customElements.define('az-register-person-step3', AZRegisterPersonStep3);
customElements.define('az-register-person-step4', AZRegisterPersonStep4);
customElements.define('az-register-person-step5', AZRegisterPersonStep5);
customElements.define('az-register-person-step6', AZRegisterPersonStep6);
customElements.define('az-products', AZProducts);
customElements.define('az-clients', AZClients);
customElements.define('az-client-product', AZClientProduct);
customElements.define('az-products-right-div', AZProductsRightDiv);
customElements.define('az-clients-right-div', AZClientsRightDiv);
customElements.define('az-filters', AZFilters);
customElements.define('az-slider', AZSlider);
customElements.define('az-switch', AZSwitch);
customElements.define('az-product', AZProduct);
customElements.define('az-client', AZClient);
customElements.define('az-menu', AZMenu);
customElements.define('az-header', AZHeader);
customElements.define('az-header-divider', AZHeaderDivider);
customElements.define('az-menu-item', AZMenuItem);
customElements.define('az-register', AZRegister);
customElements.define('az-register-left-div', AZRegisterLeftDiv);
customElements.define('az-register-right-div', AZRegisterRightDiv);
customElements.define('az-login', AZLogin);
customElements.define('az-login-left-div', AZLoginLeftDiv);
customElements.define('az-login-right-div', AZLoginRightDiv);
customElements.define('az-link', AZLink);
customElements.define('az-divider', AZDivider);
customElements.define('az-otp', AZOTP);
customElements.define('az-password', AZPassword);
customElements.define('az-button', AZButton);
customElements.define('az-input', AZInput);
customElements.define('az-radio', AZRadio);
customElements.define('az-upload', AZUpload);
customElements.define('az-select', AZSelect);
customElements.define('az-register-steps', AZRegisterSteps);
customElements.define('az-register-step', AZRegisterStep);
customElements.define('az-register-step-divider', AZRegisterStepDivider);
customElements.define('az-splash', AZSplash);
